### ISSUE TITLE
yolo detections with your deepsort trackers  

### ISSUE THREAD

**Issue by ayanasser** [levan92/deep_sort_realtime#11]
I am using yolo :
I've get the detection:
```
            detections = darknet.detect_image(network, class_names, darknet_image, thresh=args.thresh)
            for label, confidence, bbox in detections:

                  left, top, right, bottom = bbox2points(bbox)
                  if big_area_bboxs(left, top, right, bottom, 608, 608) == 0:
                      continue
                  confidence_scores.append(confidence)
                  bboxs.append([left, top, bbox[2], bbox[3]])
```
then work with the tracker:

            trackers = deepsort.update_tracks(bboxs, frame=frame_resized)
            bb_dict_curr_frame = {}
            print("trackers outside the loop: ", trackers)
            for tracker in trackers:
                print("tracker inside the loop: ", tracker)
                id_num = str(tracker.track_id)
                print("ID num: ", id_num)
                track_bb = tracker.to_tlbr()
 
And I got this error:

` Error is:     raw_detections = [d for d in raw_detections if d[0][2] > 0 and d[0][3] > 0]
TypeError: 'int' object is not subscriptable
`

Is there something I missed ?
Or the tracker needs another arguments with another shape

**Comment by levan92** [comment]
yup Kalman filter is used in DeepSORT, you can take a look at the original author's [paper](https://arxiv.org/abs/1703.07402) for more info. Code can be found at `deep_sort/kalman_filter.py`.
