### ISSUE TITLE
Clarification on how tracking works

### ISSUE THREAD

**Issue by Interpause** [levan92/deep_sort_realtime#23]
The detector I am using is quite slow, so I am wondering if this can fill in the frame gaps between detections.

To clarify, given an initial set of object detections, can I call `tracker.update_tracks` with the initial stale bboxes but with the new frame to track objects? Or am I supposed to use the Kalman-predicted bboxes?

Thanks for making this library btw.

**Comment by levan92** [comment]
Yup, `DeepSort.update_tracks()` will call `predict()` followed by `update()`. You do not need to do additional steps to access the Kalman-predicted bboxes -- the `Track.to_*` methods already give you Kalman-predicted bboxes by default. 

Just to further clarify,  the tracking algorithm comes in two parts: 1) The appearance part, which uses deep features to match appearances 2) Kalman filter part, which uses more of the bounding box states (position, velocity) and predict/propagate to future steps, aka `predict()`. This is what you're asking for in your question. 

The future frames you provide will not matter (in terms of the pixels in those frames) if you do not give any detections associated to those frames -- the forward propagated state predictions are simply based on the "historical" states of the track.

**Comment by Interpause** [comment]
I see, thanks!
