### ISSUE TITLE
Tracking with one-time object detection (One-Shot object detection and tracking)

### ISSUE THREAD

**Issue by aminromi11** [levan92/deep_sort_realtime#24]
How to detect an object only once and track it in other frames?

```
while video1.isOpened():
    ret1, frame1 = video1.read()
    if not ret1 or cv2.waitKey(60)==27:
        break

    if FlagDetect:
        boxes= PersonDetection(frame1)
        FlagDetect=False
        tracks = tracker.update_tracks(boxes, frame=frame1)

    for track in tracks:
        ltrb= track.to_ltrb()
        frame1 = cv2.rectangle(frame1, (int(ltrb[0]), int(ltrb[1])), (int(ltrb[2]), int(ltrb[3])), (255,0,0), 5)

    cv2.imshow('video1', frame1
```)

My code is not working properly!

**Comment by levan92** [comment]
DeepSORT is a multi-object tracking algorithm that is generally used in a tracking-by-detection paradigm. This means it is typically used for association of detections that are coming in every frame, and forming them into tracks. If you only want to detect once and track afterwards, you can take a look at other VOT/SOT (visual/single object tracking) works, which may be better suited for that.

**Comment by aminromi11** [comment]
Thanks.
