### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by aminromi11** [levan92/deep_sort_realtime#25]
Thank you for providing this library.
Please provide some sample code to use this library in object tracking on video.
I am still working hard with this library.

**Comment by levan92** [comment]
Sample codes are given in the README, let me know if you have any specific questions.

**Comment by RoninHunter** [comment]
Oh wait, nevermind I see what I am referencing is actually an adaptation of your project.

**Comment by RoninHunter** [comment]
What is the format that the "frame" argument of the "track.update_tracks()" is expecting?

**Comment by RoninHunter** [comment]
I see it no in the example where it says         
"frame : Optional [ np.ndarray ] = None
            if embeds not given, Image frame must be given here, in [H,W,C]."
