### ISSUE TITLE
use opencv-contrib-python-headless instead of opencv

### ISSUE THREAD

**Issue by lozybean** [levan92/deep_sort_realtime#27]
since opencv rely on libGL.so, which is not necessary when inference realtime, please use opencv-contrib-python-headless instead

**Comment by lozybean** [comment]
> Hi @lozybean, thank you for your suggestion. You can go ahead to modify `setup.py` or simply replace ur `cv2` installation with `opencv-python-headless` locally on your side. `deep_sort_realtime` should run successfully whether with `opencv-python` or `opencv-python-headless`. What I placed under `setup.py` or `requirements.txt` is just the packages most people will commonly have/use.

Thank you for your reply, I installed from pypi, would you please  use `opencv-python-headless` and publish to pypi?

**Comment by levan92** [comment]
You can do you own local changes/install your suitable dependencies in your environment, I probably won't be publishing another package just to re-specify the type of `opencv` module. Apologies about that!
