### ISSUE TITLE
Training example

### ISSUE THREAD

**Issue by YaroslavPavlovich** [levan92/deep_sort_realtime#28]
I want to make custom PyTorch model, is here any example with training code?

**Comment by levan92** [comment]
The PyTorch models used in this repo are for models to get appearance features. See [`deep_sort_realtime/embedder/embedder_pytorch.py`](deep_sort_realtime/embedder/embedder_pytorch.py). The following models are provided by default in this repo: 
1. Mobilenetv2 (pretrained imagenet): the implementation is from torchvision https://pytorch.org/vision/stable/_modules/torchvision/models/mobilenetv2.html. To train/finetune, you can follow any pytorch tutorial for training, like this: https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html. 
2. Torchreid person re-identification models: we additionally support to directly use [torchreid](https://github.com/KaiyangZhou/deep-person-reid) models. These models are specifically trained on person re-identification datasets (meaning they will be good at differentiating different person identities. Similarly, to train them, please refer to instructions on [torchreid](https://github.com/KaiyangZhou/deep-person-reid)'s repo.
