### ISSUE TITLE
Are you using the torchreid library?

### ISSUE THREAD

**Issue by kadirnar** [levan92/deep_sort_realtime#29]
Do we need to download the [Torchreid ](https://github.com/KaiyangZhou/deep-person-reid) library?

Example:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/.gitmodules#L6

**Comment by levan92** [comment]
Hi @kadirnar, apologies that I did not specify it previously. But yes, if you want to use the Torchreid embedder, please make sure `torchreid` is installed. You don't exactly have to include it as a submodule/subdirectory, just needs to be installed in your python packages. I've updated the README [dependencies section](https://github.com/levan92/deep_sort_realtime#dependencies) to reflect so. Thanks!

**Comment by kadirnar** [comment]
Thank you. I was wondering in which file you activated Torchreid. I found.

https://github.com/levan92/deep_sort_realtime/blob/master/deep_sort_realtime/embedder/embedder_pytorch.py#L142
