### ISSUE TITLE
jupyter kernel die when I create DeepSort object

### ISSUE THREAD

**Issue by M-Amrollahi** [levan92/deep_sort_realtime#31]
When I try to create an object from DeepSort, the jupyter kernel will die.
May I know where the issue is?

**Comment by levan92** [comment]
It's hard to determine what's the problem without any error msg or logs. Maybe try directly running a similar code segment in a python script in terminal and see if you can run?

**Comment by M-Amrollahi** [comment]
That is right. I have run it again on new env and it works.
Thanks
