### ISSUE TITLE
Multiple Images or Cameras

### ISSUE THREAD

**Issue by hafidh561** [levan92/deep_sort_realtime#32]
Hello, I have questions about, How to implement deep sort with multiple images or cameras with different views? Because the readme doesn't have a configuration for multiple images or cameras with different views, just only single images or cameras. Thanks

**Comment by romarcg** [comment]
If I understood your question, you should add your own frame reading logic to the readme example, like so:

```

from deep_sort_realtime.deepsort_tracker import DeepSort
# define your deepsort tracker
tracker = DeepSort(max_age=5)

# initialize your frame reader (e.g., individual file data loader, opencv video stream)
reader = init_reader()
# read frame and process it until end_condition is met, e.g., no more frames in video
while (not end_condition):
  # read frame
  frame = reader.read_frame()
  # detect objects in frame
  bbs = object_detector.detect(frame) 
  tracks = tracker.update_tracks(bbs, frame=frame) # bbs expected to be a list of detections, each in tuples of ( [left,top,w,h], confidence, detection_class )
  for track in tracks:
      if not track.is_confirmed():
          continue
      track_id = track.track_id
      ltrb = track.to_ltrb()
  # update end_condition

reader.close_reader()
```

**Comment by hafidh561** [comment]
> Multi-object tracking algorithms like DeepSORT here works within the context of one camera view. You may independently run an instance of DeepSORT for each of your cameras, that is up to your implementation. If you want to track across different cameras, then that's another task -- you may want to check out person re-identification algorithms and build your own re-id engine.

Thanks, so if I use weights from person re-id and use DeepSORT it's actually not working, am I right?

**Comment by hafidh561** [comment]
> If I understood your question, you should add your own frame reading logic to the readme example, like so:
> 
> ```
> 
> from deep_sort_realtime.deepsort_tracker import DeepSort
> # define your deepsort tracker
> tracker = DeepSort(max_age=5)
> 
> # initialize your frame reader (e.g., individual file data loader, opencv video stream)
> reader = init_reader()
> # read frame and process it until end_condition is met, e.g., no more frames in video
> while (not end_condition):
>   # read frame
>   frame = reader.read_frame()
>   # detect objects in frame
>   bbs = object_detector.detect(frame) 
>   tracks = tracker.update_tracks(bbs, frame=frame) # bbs expected to be a list of detections, each in tuples of ( [left,top,w,h], confidence, detection_class )
>   for track in tracks:
>       if not track.is_confirmed():
>           continue
>       track_id = track.track_id
>       ltrb = track.to_ltrb()
>   # update end_condition
> 
> reader.close_reader()
> ```

Sorry if my question it's not clear enough. I mean another camera view, not just a single camera. If using this, it's not working in multiple camera views.

**Comment by levan92** [comment]
> > Multi-object tracking algorithms like DeepSORT here works within the context of one camera view. You may independently run an instance of DeepSORT for each of your cameras, that is up to your implementation. If you want to track across different cameras, then that's another task -- you may want to check out person re-identification algorithms and build your own re-id engine.
> 
> 
> 
> Thanks, so if I use weights from person re-id and use DeepSORT it's actually not working, am I right?

If you're using person re-id appearance embedder for your deepsort tracking, then I think it should be reasonable for you to to re-use these features from each track for re-identification across different cameras. But do note that in this repo, we use a light re-id network for appearance embedding by design. For person re-id across cameras, people may want to use deeper re-id networks for more discriminative ability. End of the day, it's up to your design considerations.

**Comment by hafidh561** [comment]
> 

Thank's for your answers. It's clear to me. I hope you have a great day.
