### ISSUE TITLE
A more in-depth understanding of the matching step

### ISSUE THREAD

**Issue by ignaciomendizabal** [levan92/deep_sort_realtime#33]
First of all, i would like to say thank you for making this implementation of the DeepSORT algorithm.

I'd like to use DeepSORT to track objects for a few frames since our detector is slow. I saw a new commit to the repo which allows to call `update_tracks()` without detections. My guess is that, in that case, the algorithm predicts the bounding box from previous kalman filter estimations (by calling `predict()`), and doesn't run the matching cascade (the `update()` functions doesn't do anything as there are no detections), so each track simply follow the kalman estimation until a new detection is found. When that happens, the algorithm runs the kalman filter again and matches tracks with detections. Is that right?

Another issue i had with the original paper is the use of the Mahalanobis distance. From what i understood the algorithm runs the matching cascade using both the mahalanobis distance and the deep appearance metric obtained from the pretrained CNN, then calculates IoU for matching unmatched tracks from the previous step, is that right?

Thank you for your help.

**Comment by levan92** [comment]
Hi, thank you for your interest! 

> When that happens, the algorithm runs the kalman filter again and matches tracks with detections. Is that right?

yup your understanding is correct here. 

> From what i understood the algorithm runs the matching cascade using both the mahalanobis distance and the deep appearance metric obtained from the pretrained CNN, then calculates IoU for matching unmatched tracks from the previous step, is that right?

Yup seems like your understanding is correct here as well. Roughly speaking:
1. Appearance distance matrix $D$ is computed
2. Gating is performed via Mahalanobis distance (between predicted KF and measurements), which sets those entries above threshold in $D$ to infinity. 
3. Assignment based on $D$
4. Unmatched tracks, unmatched detections undergo last round of matching via IoU.

**Comment by ignaciomendizabal** [comment]
Thank you for your help! that answered my question
