### ISSUE TITLE
custom max_iou_distance

### ISSUE THREAD

**Issue by visual-engines** [levan92/deep_sort_realtime#36]
The `max_iou_distance` parameter in the `Tracker` initializer is always 0.7, since the `DeepSort` instance sets `self.tracker` without specifying an explicit value for that parameter; hence the default value is used.  

Could someone let `max_iou_distance` customizable through an additional `DeepSort` init parameter, just like `max_age`, `n_init` and so on?

This change would be very useful if deep_sort_realtime is imported after having installed it using `setup.py`

Thank you very much

**Comment by levan92** [comment]
Hi @visual-engines, sorry for the delay, this has been fixed in this recent commit: 2491e6dc326927b3fed8169a0bacb4a4ef2da4f9. `max_iou_distance` is exposed as an argument for the `DeepSort` class.
