### ISSUE TITLE
Identity switch

### ISSUE THREAD

**Issue by shamindraparui** [levan92/deep_sort_realtime#37]
Hi, I am using Yolo5 (Person class) with DeepSortRealtime.  Tracking is happening but identity of person(s) switches even when really short occlusion occurs (between person-person, person-object). I have checked the result with CLIP embedder, `max_age` parameter, no luck. Can anyone provide some suggestions on minimizing the identity switch?

**Comment by DCCCXIX** [comment]
Any success on solving this problem?

**Comment by romarcg** [comment]
Have you computed the feature distance distribution between correct and incorrect identities in your target scenario? This can help you to correctly choose the proper `max_cosine_distance` parameter used in the first association step (gating distance + appearance distance).

https://github.com/levan92/deep_sort_realtime/blob/f11a5869ccd669338aacf6f19364b7cd3596b89f/deep_sort_realtime/deep_sort/tracker.py#L151

The default distance gating will consider close measurements (detections) to the projected track. If your `max_cosine_distance` is too broad, it might result in an incorrect linear assignment and an identity switch. 

Also, this might be related to an unconfirmed issue when comparing new detection features to the confirmed track feature histories.

**Comment by Jordan-Pierce** [comment]
Hi @romarcg, is there a specific way of computing this beforehand?
