### ISSUE TITLE
cv2.imshow broken when using tracker

### ISSUE THREAD

**Issue by superfast852** [levan92/deep_sort_realtime#39]
Hello. When i use the realtime deepsort tracker, the program freezes when trying to run cv2.imshow. If i remove the function, the code runs fine. Any help?

**Comment by levan92** [comment]
That seems to be a opencv (cv2) issue, you might want to google around for the issue. In general, maybe check that you have a gui to display your imshow and that you're running your `imshow` correctly with other supporting functions like `cv2.waitKey`
