### ISSUE TITLE
np.float deprecated

### ISSUE THREAD

**Issue by mpautzke-nexplore** [levan92/deep_sort_realtime#40]
In the latest version of deep_sort_realtime (1.3.1) within deepsort/detection.py there was the use of np.float which was deprecated in numpy version 1.20.  I saw that the master branch already addressed this issue.  Is there a release planned in the near future?

Thanks!

**Comment by levan92** [comment]
Hi, thank you for your interest. Sure, sorry for the delay, I think I might be able to get a release out this weekend!

**Comment by levan92** [comment]
v1.3.2 has been published

**Comment by mpautzke-nexplore** [comment]
Thanks!!!
