### ISSUE TITLE
TF Google Drive Link 

### ISSUE THREAD

**Issue by nathanallen242** [levan92/deep_sort_realtime#49]
The current link to access the pre-trained weights for the TF embedding is currently unavailable: https://drive.google.com/file/d/1RBroAFc0tmfxgvrh7iXc2e1EK8TVzXkA/view?usp=sharing

Is there any external resources where I can access these weights? What are my options?

Thank you!

**Comment by levan92** [comment]
You can find support directly from the original model developer: https://github.com/JonathanCMitchell/mobilenet_v2_keras/releases/tag/v1.1
