### ISSUE TITLE
What is object_detector and how to use it?

### ISSUE THREAD

**Issue by Rich2020** [levan92/deep_sort_realtime#54]
Hi!

In the example code there is this line:

`bbs = object_detector.detect(frame) `

but `object_detector` is not described anywhere. Can we use any object detector that returns `([x,y,w,h], conf, class)`?

Is there a complete example somewhere?

**Comment by levan92** [comment]
Yup, just make sure the inputs are formatted as expected (refer to the comment in the example code or you can take a look at the source code).
