### ISSUE TITLE
tracked object last location

### ISSUE THREAD

**Issue by Hilal-Urun** [levan92/deep_sort_realtime#9]
Hi, I'm trying to find last location of tracked object on IP Camera with adding object id and tracked loc taked from to_tlbr() function than grouped locations according to id's and access last location of the object according to the id. Because its leave and last loc always updated I do not handle with this problem. Could you guide me please, I'm lost :)
Thanks for your time..

**Comment by levan92** [comment]
Please see example given here: https://github.com/levan92/deep_sort_realtime#run

`ltrb = track.to_ltrb()` will get you the latest bounding box of your track. Do note that if you want to get back the bounding box of the original given detection, you can additionally flag `track.to_ltrb(orig=True)`.

Let me know if that helps. Thanks.

**Comment by levan92** [comment]
Will be closing the issue, we can re-open if you have any other questions.
